---
- name: Install and start httpd service
  hosts: client
  tasks:
   - name: httpd package is present
     yum:
        name: httpd
        state: present
   - name: httpd service
     service: 
       name: httpd
       state: started
       enabled: yes
